name: production
url: https://api.e-harmony.com
secrets:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
protection_rules:
  - type: required_reviewers
    required_reviewer_count: 1
